### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by lbt0116** [edantec/simple-mpc#2]
When I run the tests, I met this error:
unknown location(0): fatal error: in "problem/fulldynamics": memory access violation at address: 0x0: no mapping at fault address

**Comment by EtienneAr** [comment]
Hello,
Thank you for your interest in our software.
Unfortunately, the package is still in alpha version and will be greatly reworked in the upcoming month. (it also uses some private dependencies that will need to be either published publicly or replaced).
