### ISSUE TITLE
jrl-cmakemodules as a submodule?

### ISSUE THREAD

**Issue by ManifoldFR** [edantec/simple-mpc#3]
Currently, the contents of https://github.com/jrl-umi3218/jrl-cmakemodules/ are directly vendored into this repo, instead of as a submodule, as we usually do in our projects (aligator, proxsuite, pinocchio...)

- is this intended?
- can/should we switch to a submodule?

cc @edantec

**Comment by edantec** [comment]
It is not intended, we should definitely switch to a submodule.

**Comment by ManifoldFR** [comment]
Okay, I'll add this to #4
